### PR TITLE
Adds OpenTelemetry safe helper functions

### PR DESCRIPTION
**Pull request by TheAngryByrd**
## Proposed Changes

[Best practices](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#best-practices-2) indicate we should be doing null checks against OpenTelemetry functions.  Since F# doesn't have the `?.` operator, we need helper functions.

Bigger question... should this live in this repository?

## Types of changes

What types of changes does your code introduce to FsLibLog?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by baronfel** [comment]
I think it should live elsewhere for two reasons:

* It's not connected to FsLibLog conceptually, and
* it forces architectural changes (targeting net5.0) because the types aren't in .netstandard2.0/2.1

I am excited to see these, though. The default addition of line info is 👨‍🍳 💋

**Comment by TheAngryByrd** [comment]
> It's not connected to FsLibLog conceptually, and

One could argue it is since they're connected at the "observability" level but FsLibLog is just currently scoped at logging. So is it a good idea for this repo to become broader in scope. (This isn't a strong opinion, just devil's advocating) 

> it forces architectural changes (targeting net5.0) because the types aren't in .netstandard2.0/2.1

Yeah I was considering a separate project file just because of that.

**Comment by TheAngryByrd** [comment]
Ok I threw it in a separate project as a concept.  

I do think a different repository is a better idea since I'd probably want to "version" this separately as it independent from a code perspective .Although they're starting to share some semantics like `getLoggerForFunc` and `StartActivityForFunc`.

**Comment by TheAngryByrd** [comment]
I decided to make it's own repository: https://github.com/TheAngryByrd/FsOpenTelemetry

Follow over there.

**Pull request closed without merging**
